### PR TITLE
forgot password page, renders only once

### PR DESCRIPTION
**Pull request by Sbonelo01**
Related issues: [RENDER tidy]

## I solemnly swear that:

- [x] My code follows the style guidelines of this project
- [x] I have merged the develop branch into my branch and fixed any merge conflicts
- [x] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Sbonelo01** [comment]
There are no re-renders here. I did some clean code fixes

**Review by Ngoakor12 — APPROVED** [review]
No unnecessary re-renders found.

**Review by Ngoakor12 — APPROVED** [review]
No unnecessary re-renders found.

**Review by Ngoakor12 — APPROVED** [review]
No unnecessary re-renders found.

**Review by KhalidUmuzi — APPROVED** [review]

**Review by sheenarbw — APPROVED** [review]

**Pull request merged**
