### PR TITLE
aligned buttons and titles with the same margin

### LINKED ISSUE #229: Teams/People cards: Align Tittle and the buttons in users  cards
### Description:

Can you align the Tittles and Buttons with pull requests and Review cards texts

This is to have a consistent left alignment for the texts and the buttons in the Teams cards

### Steps to reproduce:

1. On your users board
2. Add a margin-top of 8px, in your titles
3.  add a margin-left of 16px got your titles and buttons
4.  Rename People to Users
5.   Increase the width of the search input field, can also use a width of 62px
6.    Make sure you also same left margin in the People/Users cards buttons and headings
7.    Make sure in all cards, Count and Oldest are inline irrespective if the card has a date or not
8.  On your Dashboard Page, also make the Performance to be centred
### Expected behavior:

Screenshot 2021-11-03 at 20 11 09

Screenshot 2021-11-03 at 20 58 45

### Actual behavior:

Screenshot 2021-11-03 at 20 18 24

Screenshot 2021-11-03 at 21 07 38

Screenshot 2021-11-03 at 20 52 57

### Client Setup Information

- Browser Version:
- Operating System:

### PR DESCRIPTION
**Pull request by kaleem99**
Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by kaleem99** [comment]
Screenshot 2021-11-10 220022

**Review by Vuyisanani — CHANGES_REQUESTED** [review]
Hi @kaleem99 

Please consider other changes as requested on the task

- Rename People to Users
- Increase the width of the search input field, can also use a width of 62px
- Make sure you also same left margin in the People/Users cards buttons and headings
- Make sure in all cards, Count and Oldest are inline irrespective if the card has a date or not
- On your Dashboard Page, also make the Performance to be centred

Should you request clarity I am happy to chat

**Comment by kaleem99** [comment]
screenshot1

**Comment by kaleem99** [comment]
screenshot2

**Review by Vuyisanani — APPROVED** [review]

**Review by Sbonelo01 — APPROVED** [review]
Looks good

**Review by sheenarbw — COMMENTED** [review]
This is confusing. The PR and the linked issue seem to have very little to do with each other.

Was the issue misunderstood? Or should this be linked to a different issue?

**Review by babalwa-mbolekwa — APPROVED** [review]

**Review by babalwa-mbolekwa — CHANGES_REQUESTED** [review]
Hey Kaleem. Please also fix the alignment so that the email is fully displayed
titleButtons

**Comment by Vuyisanani** [comment]
Hi @kaleem99 

This is looking good, just the styling, can we rather have our styles in classes, rather than having them in-line and others in classes

**Pull request merged**
