### PR TITLE
Resized Cards

### PR DESCRIPTION
**Pull request by seebuudaa**
the cards are of the same size 

Screenshot from 2020-08-14 13-47-13

### CODE REVIEW

**Comment by Shaheedah** [comment]
Hey Sbu :) please check the screenshot, these are the project cards that need to be resized
Screenshot from 2020-08-18 15-16-09

**Review by XolaniMgube — COMMENTED** [review]
Fede Sbu, I'm a bit confused here. 
I see you made the changes in the frontend directory rather than experimental frontend, I post this as a question also because I'm also not sure where you should've made changes.

Another thing I'm not sure of again, but I think you should have some sort of data in order to know how those cards are suppose to be sized. Please correct me.

**Comment by Lisa1400** [comment]
I agree with Shaheedah. If you're not sure as to which folder you should be working on in future please don't hesitate to ask us. It can be confusing sometimes.

**Review by Portia-arch — COMMENTED** [review]
I agree with Shaheeda also. The cards were shown to is during sprint planning  I think you should have asked which folder you supposed to work on before editing existing code.

**Pull request closed without merging**
