### PR TITLE
move the fire

### PR DESCRIPTION
**Pull request by TheMaja**
- initial commit burndwon chart move to actions
- moved fire chart from the dashboard column to the actions column
- cleanup

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [x] My code follows the style guidelines of this project
- [x] I have merged the develop branch into my branch and fixed any merge conflicts
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Sbonelo01 — APPROVED** [review]

**Review by Sbonelo01 — CHANGES_REQUESTED** [review]
Please dismiss my approving review 

Please make sure that we match the style-guide. i,e from `Presentation.js` to `Presentation.jsx` and so forth.

**Review by Sbonelo01 — APPROVED** [review]

**Review by KhalidUmuzi — APPROVED** [review]

**Review by sheenarbw — CHANGES_REQUESTED** [review]
It looks ok but I haven't properly tested it. There is one strange thing happening here:

Are you sure you meant to update package-lock?  Did you install something new?

If you did mean to change it can you please give some details. And if you dfid not mean to change it (which seems more likely to me) then can you please make sure it is not mentioned in your PR.

**Review by Sbonelo01 — APPROVED** [review]

**Review by Sbonelo01 — CHANGES_REQUESTED** [review]
Please fix the merge conflicts

**Review by Sbonelo01 — APPROVED** [review]

**Comment by KhalidUmuzi** [comment]
Since the task isn't to really match the style guide by moving the userActions component into the pages directory, I think I can allow this to remain. @sheenarbw let me know if you agree or not.

**Review by KhalidUmuzi — APPROVED** [review]

**Review by sheenarbw — APPROVED** [review]
I did a little cleanup just to move this along

**Pull request merged**
