### PR TITLE
Feat/dont create umuzi user automatically

### LINKED ISSUE #42: When a user logs in with an Umuzi email address, prevent it from automatically creating a user
This used to be an Umuzi-specific project, but this is no longer the case. Also auto-creating users for @umuzi logins has caused a few problems and confusions for users. Like "my board is empty because I logged in with a completely seperate email address". 

Currently: When a user logs in with their umuzi email address then a user is automatically created if it didn't exist. This is not the correct behavior. 

Do not automatically create any User instances when people log in. 

Please remove that functionality

### PR DESCRIPTION
**Pull request by Andy-Nkumane**
Related issues: When a user logs in with an Umuzi email address, prevent it from automatically creating a user #42

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by sheenarbw** [comment]
Hey @Andy-Nkumane . It looks good. 

Did you run the unit tests?

**Comment by Andy-Nkumane** [comment]
@sheenarbw I hadn't run unit tests - will it be fine if I remove the test `test_internal_email_user_does_not_exist`?

**Review by sheenarbw — APPROVED** [review]

**Comment by sheenarbw** [comment]
@Andy-Nkumane The unit tests don't pass so I'm going to have to revert this

**Comment by Andy-Nkumane** [comment]
> @Andy-Nkumane The unit tests don't pass so I'm going to have to revert this

@sheenarbw made a new pr - tests pass

**Pull request merged**
