### PR TITLE
Polish burndown chart refactor

### LINKED ISSUE #448: Make a person's BurnDown chart show up on their dashboard
A bunch of work has already happened on this. There is a burndown component and an API and all sorts of nice things. Just polish it up.

Note that we don't currently store start and end dates for a learner. So don't worry about those. We just need to display the graph without any ideal burn rate

### PR DESCRIPTION
**Pull request by KhalidUmuzi**
Related issues: [please specify]

## Description:

Made burndown chart visible on the dashboard

## I solemnly swear that:

- [x] My code follows the style guidelines of this project
- [x] I have merged the develop branch into my branch and fixed any merge conflicts
- [x] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Sbonelo01 — CHANGES_REQUESTED** [review]
This looks good, I think it's well-positioned, from a learner's perspective. 

I would like to point out that currently, it is unresponsive - maybe that can be handled in another PR or issue


I think the burndown chart could use a little padding between the chart keys and the chart dates.
See:
Screenshot_2022-06-13_11-30-20(burndown-review)

**Comment by KhalidUmuzi** [comment]
Hmmm. On my side it looks fine. I remember adding padding already. This is what it looks like on my side
image

**Review by Sbonelo01 — APPROVED** [review]
I will approve, but it still looks the same on my side

**Review by FaithMo — APPROVED** [review]
its padded on my side

**Pull request merged**
