### PR TITLE
Close button to modal widget

### LINKED ISSUE #402: Add a close button to the Modal widget
src/components/widgets/Modal.js 

Add an X to the top right of the widget with `onClick={onClose}` 

Make sure that the whole file matches the styleguide

### PR DESCRIPTION
**Pull request by babalwa-mbolekwa**
Related issues: [#402 ]

## Description:

What are you up to? Fill us in :)

## Screenshots/videos
closeButton

## I solemnly swear that:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Sbonelo01 — CHANGES_REQUESTED** [review]
This looks very good

can we please work on making it responsive to mobile 

Screenshot_2022-03-23_12-39-21(Babalwa-review)

**Review by Sbonelo01 — CHANGES_REQUESTED** [review]
This looks good and is responsive.

Please have a look at the style guide regarding file extensions and how to name functional components: https://github.com/Umuzi-org/Tilde/blob/develop/frontend/STYLE_GUIDE.md

**Review by kaleem99 — APPROVED** [review]

**Review by Sbonelo01 — APPROVED** [review]

**Review by KhalidUmuzi — APPROVED** [review]

**Review by KhalidUmuzi — CHANGES_REQUESTED** [review]
So with this change it doesn't affect any other modals on Tilde but only this one.

I believe that for consistency, all modals on tilde should have the same behavior so if we apply this change here, we apply it everywhere.

in the filepath frontend/src/widgets there is a file called Modal.js

That is used in a number of places and the change should be made to this modal and filter through to all other modals on Tilde.

And example of this is https://github.com/Umuzi-org/Tilde/pull/338. According to a comment made on this issue, this change is made to address that modal as well. It does not.

**Comment by babalwa-mbolekwa** [comment]
> So with this change it doesn't affect any other modals on Tilde but only this one.
> 
> I believe that for consistency, all modals on tilde should have the same behavior so if we apply this change here, we apply it everywhere.
> 
> in the filepath frontend/src/widgets there is a file called Modal.js
> 
> That is used in a number of places and the change should be made to this modal and filter through to all other modals on Tilde.
> 
> And example of this is #338. According to a comment made on this issue, this change is made to address that modal as well. It does not.

@KhalidUmuzi The styling doesn't work out when I try to style the addReviewModal or the Modal itself. The width of the addReview modal remains the same. I think there's a number of things that need to be changed in the background in addition to what we changed

**Review by Vuyisanani — APPROVED** [review]

**Review by sheenarbw — APPROVED** [review]
weeee

**Pull request merged**
