### PR TITLE
fixed broken story ticket 302

### LINKED ISSUE #302: Fix broken story at http://localhost:6006/?path=/story/tilde-carddetails-projectdetails--primary
This one is a bit tricky. It will likely require a refactor

### PR DESCRIPTION
**Pull request by kaleem99**
Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by FaithMo — APPROVED** [review]

**Review by Sbonelo01 — APPROVED** [review]

**Review by babalwa-mbolekwa — CHANGES_REQUESTED** [review]
Hey Kaleem could you please check if the props in the story match the ones in the Presentation file and ensure that the data used is up to date with the current used on Tilde. You can login into the Tilde that is already in production and use Redux dev tools to check how the different objects look and copy that data, e.g. if you look inside the Presentation file for ProjectDetails it no longer uses `reviewIds`. You can also use sample data for `projectReviews` from Redux dev tools. Check **state -> apiEntities**

**Comment by kaleem99** [comment]
image

**Review by FaithMo — APPROVED** [review]
Changes addressed

**Review by Sbonelo01 — COMMENTED** [review]
Something looks wrong with how the review is getting rendered. Is it wrapped inside a `Typography` component? I think it should be

**Review by Sbonelo01 — APPROVED** [review]
Since you should not edit any other files, it looks good.

**Review by babalwa-mbolekwa — APPROVED** [review]

**Review by sheenarbw — APPROVED** [review]

**Pull request merged**
